# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/allnicevivi"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "instagram"
    name       = "Instagram"
    url        = "https://instagram.com/allnicevivi"

    [social.params]
        icon = "brand-instagram"

[[social]]
    identifier = "email"
    name       = "Email"
    url        = "mailto:allnicevivi@gmail.com"

    [social.params]
        icon = "mail"
